miniorange_saml.settings:
  type: mapping
  label: Settings
  mapping:
    miniorange_saml_customer_admin_email:
      type: 'NULL'
    miniorange_saml_license_key:
      type: 'NULL'
    miniorange_saml_customer_id:
      type: string
    miniorange_saml_customer_admin_token:
      type: string
    miniorange_saml_customer_api_key:
      type: string
    miniorange_saml_force_auth:
      type: boolean
    miniorange_saml_enable_backdoor:
      type: boolean
    miniorange_saml_default_relaystate:
      type: string
    miniorange_saml_idp_name:
      type: string
    miniorange_saml_idp_issuer:
      type: string
    miniorange_saml_nameid_format:
      type: string
    miniorange_saml_idp_login_url:
      type: string
    miniorange_saml_idp_logout_url:
      type: string
    miniorange_saml_idp_certificate:
      type: string
    miniorange_saml_enable_login:
      type: boolean
    miniorange_saml_username_attribute:
      type: string
    miniorange_saml_email_attribute:
      type: string
    miniorange_saml_idp_attr1_name:
      type: string
    miniorange_saml_attr5_name:
      type: string
    miniorange_saml_idp_attr5_name:
      type: string
    miniorange_saml_attr2_name:
      type: string
    miniorange_saml_idp_attr2_name:
      type: string
    miniorange_saml_attr3_name:
      type: string
    miniorange_saml_idp_attr3_name:
      type: string
    miniorange_saml_attr4_name:
      type: string
    miniorange_saml_idp_attr4_name:
      type: string
    miniorange_saml_disable_autocreate_users:
      type: boolean
    miniorange_saml_default_role:
      type: string
    miniorange_saml_role1_name:
      type: string
    miniorange_saml_idp_role1_name:
      type: string
    miniorange_saml_role2_name:
      type: string
    miniorange_saml_idp_role2_name:
      type: string
    miniorange_saml_role3_name:
      type: string
    miniorange_saml_idp_role3_name:
      type: string
    miniorange_saml_role4_name:
      type: string
    miniorange_saml_idp_role4_name:
      type: string
    miniorange_saml_status:
      type: string
    miniorange_saml_customer_admin_phone:
      type: 'NULL'
    miniorange_saml_tx_id:
      type: 'NULL'
    miniorange_saml_customer_admin_password:
      type: string
    miniorange_saml_auto_redirect_to_idp:
      type: boolean
    miniorange_saml_sp_issuer:
      type: string
    miniorange_saml_login_by:
      type: integer
    miniorange_saml_attr1_name:
      type: string
    miniorange_saml_slo_http_binding:
      type: string
    miniorange_saml_http_binding:
      type: string
    miniorange_saml_backdoor_url_query:
      type: string
    mo_saml_metadata_OrganizationName:
      type: string
    mo_saml_OrganizationDisplayName:
      type: string
    mo_saml_OrganizationURL:
      type: string
    mo_saml_ContactPersonTechnicalName:
      type: string
    mo_saml_ContactPersonTechnicalEmail:
      type: string
    mo_saml_ContactPersonSupportName:
      type: string
    mo_saml_ContactPersonSupportEmail:
        type: string
    miniorange_saml_send_slo_in_iframe:
      type: boolean
    miniorange_saml_enable_attribute_restriction:
      type: boolean
    miniorange_saml_attribute_based_rules:
      type: string
    miniorange_saml_load_user:
      type: string
    miniorange_saml_default_redirect_url_after_logout:
      type: string
    miniorange_saml_isMultiSitePluginRequested:
      type: string
    miniorange_saml_character_encoding:
      type: boolean
    miniorange_saml_custom_attrs_map_arr:
       type: string
    miniorange_saml_custom_attrs_map_sep:
       type: string
